INSERT ALL
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Woven wear', 2021, 33.3, '+6')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Woven wear', 2022, 38.6, '-7')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Woven wear', 2023, 39.1, '-3')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('For men or boys', 2021, 11.6, '+9')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('For men or boys', 2022, 13.1, '-9')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('For men or boys', 2023, 13.0, '-5')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('For women or girls', 2021, 21.8, '+5')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('For women or girls', 2022, 25.6, '-6')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('For women or girls', 2023, 26.1, '-2')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Knitwear', 2021, 17.3, '-1')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Knitwear', 2022, 16.9, '-22')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Knitwear', 2023, 16.4, '-7')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('For men or boys (Knitwear)', 2021, 6.2, '-15')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('For men or boys (Knitwear)', 2022, 7.0, '-9')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('For men or boys (Knitwear)', 2023, 6.7, '-8')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('For women or girls (Knitwear)', 2021, 11.1, '+9')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('For women or girls (Knitwear)', 2022, 9.9, '-28')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('For women or girls (Knitwear)', 2023, 9.7, '-7')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Clothing accessories', 2021, 7.0, '-1')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Clothing accessories', 2022, 7.1, '-19')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Clothing accessories', 2023, 7.8, '+5')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Of textile fabrics', 2021, 2.5, '-5')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Of textile fabrics', 2022, 2.4, '-21')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Of textile fabrics', 2023, 2.9, '+15')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Of non-textile fabrics', 2021, 4.6, '+1')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Of non-textile fabrics', 2022, 4.7, '-17')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Of non-textile fabrics', 2023, 4.9, '0')  
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Other apparel articles', 2021, 42.4, '+7')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Other apparel articles', 2022, 37.3, '-29')
    INTO ApparelStatistics (Category, Year, Share_Percentage, Growth_Percentage) VALUES ('Other apparel articles', 2023, 36.7, '-6')
SELECT * FROM dual;